name: Ping Supabase Every 5 Days

on:
  schedule:
    # Run every 5 days at 8 AM UTC
    - cron: "0 8 */5 * *"
  workflow_dispatch: # Allows manual runs

jobs:
  ping-supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Send ping request
        id: ping
        run: |
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" "https://wild-oasis-customer-facing-website-fawn.vercel.app/api/ping")
          if [ "$RESPONSE" -ne 200 ]; then
            echo "Ping failed with status $RESPONSE"
            exit 1
          fi
          echo "Ping successful with status $RESPONSE"

      - name: Send Email if Ping Fails
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Supabase Ping Failed!"
          to: ekekwecharles50@gmail.com
          from: "GitHub Actions <ekekwecharles50@gmail.com>"
          body: "The ping to your Supabase project failed. Please check the API endpoint."
